#!/bin/bash

# http://brew.sh/

defaults write com.apple.finder AppleShowAllFiles YES
defaults write NSGlobalDomain KeyRepeat -int 1
defaults write -g InitialKeyRepeat -int 12

# disable the swiping to go back in chrome
defaults write com.google.Chrome AppleEnableSwipeNavigateWithScrolls -bool FALSE

xcode-select --install

[ -d ~/projects ] || mkdir ~/projects

zsh_path=`which zsh`

if [ $SHELL != $zsh_path ]; then
  chsh -s $zsh_path
fi

sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

export PATH=/usr/local/bin:/usr/local/sbin:$PATH

brew install vim --with-override-system-vi
brew install coreutils
brew install\
  cask\
  git\
  node\
  mysql\
  redis\

brew cask install --appdir="/Applications"
  firefox\
  atom\
  flux\
  vlc\
  caffeine\
  google-chrome\
  iterm2\
  slack\
  viscocity
  
pip install virtualenv

# if [ ! -d ~/dotfiles ]; then
#   (cd ~ && git clone https://);
# fi
